export const allSocials = [
  {
    id: "1",
    title: "amazon",
    icon: "amazon",
    placeholder: "https://amazon.com/shop/name",
  },
  {
    id: "2",
    title: "android",
    icon: "android",
    placeholder: "",
  },
  {
    id: "3",
    title: "app",
    icon: "apple",
    placeholder: "",
  },
  {
    id: "4",
    title: "baidu",
    icon: "baidu",
    placeholder: "",
  },
  {
    id: "5",
    title: "bandcamp",
    icon: "bandcamp",
    placeholder: "https://bandcamp.com/username",
  },
  {
    id: "6",
    title: "behance",
    icon: "behance",
    placeholder: "https://behance.net/username",
  },
  {
    id: "7",
    title: "blogger",
    icon: "blogger",
    placeholder: "https://username.blogspot.com",
  },
  {
    id: "8",
    title: "bluesky",
    icon: "bluesky",
    placeholder: "",
  },
  {
    id: "9",
    title: "chrome",
    icon: "chrome",
    placeholder: "",
  },
  {
    id: "10",
    title: "codepen",
    icon: "codepen",
    placeholder: "https://codepen.io/username",
  },
  {
    id: "11",
    title: "coffee",
    icon: "coffee",
    placeholder: "",
  },
  {
    id: "12",
    title: "discord",
    icon: "discord",
    placeholder: "https://discord.gg/invitecode",
  },
  {
    id: "13",
    title: "dribble",
    icon: "dribble",
    placeholder: "https://dribbble.com/username",
  },
  {
    id: "14",
    title: "drive",
    icon: "drive",
    placeholder: "",
  },
  {
    id: "15",
    title: "dropbox",
    icon: "dropbox",
    placeholder: "",
  },
  {
    id: "16",
    title: "email",
    icon: "email",
    placeholder: "email@example.com",
  },
  {
    id: "17",
    title: "facebook",
    icon: "facebook",
    placeholder: "https://facebook.com/username",
  },
  {
    id: "18",
    title: "figma",
    icon: "figma",
    placeholder: "https://figma.com/@username",
  },
  {
    id: "19",
    title: "gift-card",
    icon: "gift-card",
    placeholder: "",
  },
  {
    id: "20",
    title: "google-drive",
    icon: "google-drive",
    placeholder: "",
  },
  {
    id: "21",
    title: "google-store",
    icon: "google-store",
    placeholder: "",
  },
  {
    id: "22",
    title: "hangout",
    icon: "hangout",
    placeholder: "",
  },
  {
    id: "23",
    title: "instagram",
    icon: "instagram",
    placeholder: "https://instagram.com/username",
  },
  {
    id: "24",
    title: "linkedin",
    icon: "linkedin",
    placeholder: "https://linkedin.com/in/username",
  },
  {
    id: "25",
    title: "medium",
    icon: "medium",
    placeholder: "https://medium.com/@username",
  },
  {
    id: "26",
    title: "phone",
    icon: "phone",
    placeholder: "+1234567890",
  },
  {
    id: "27",
    title: "podcast",
    icon: "podcast",
    placeholder: "",
  },
  {
    id: "28",
    title: "reddit",
    icon: "reddit",
    placeholder: "https://reddit.com/u/username",
  },
  {
    id: "29",
    title: "shopify",
    icon: "shopify",
    placeholder: "",
  },
  {
    id: "30",
    title: "snapchat",
    icon: "snapchat",
    placeholder: "https://snapchat.com/add/username",
  },
  {
    id: "31",
    title: "soundcloud",
    icon: "soundcloud",
    placeholder: "https://soundcloud.com/username",
  },
  {
    id: "32",
    title: "spotify",
    icon: "spotify",
    placeholder: "https://open.spotify.com/user/username",
  },
  {
    id: "33",
    title: "steam",
    icon: "steam",
    placeholder: "",
  },
  {
    id: "34",
    title: "strava",
    icon: "strava",
    placeholder: "",
  },
  {
    id: "35",
    title: "telegram",
    icon: "telegram",
    placeholder: "https://t.me/username",
  },
  {
    id: "36",
    title: "threads",
    icon: "threads",
    placeholder: "",
  },
  {
    id: "37",
    title: "tiktok",
    icon: "tiktok",
    placeholder: "https://tiktok.com/@username",
  },
  {
    id: "38",
    title: "tumblr",
    icon: "tumblr",
    placeholder: "https://username.tumblr.com",
  },
  {
    id: "39",
    title: "twitter",
    icon: "twitter",
    placeholder: "https://twitter.com/username",
  },
  {
    id: "40",
    title: "whatsapp",
    icon: "whatsapp",
    placeholder: "https://wa.me/1234567890",
  },
  {
    id: "41",
    title: "youtube",
    icon: "youtube",
    placeholder: "https://youtube.com/c/username",
  },
  {
    id: "42",
    title: "music",
    icon: "music",
    placeholder: "",
  },
];
